FROM --platform=linux/amd64 ubuntu:latest

WORKDIR /user

RUN apt-get update && \
    apt-get install -y \
    build-essential \
        cmake \
        git \
        g++ \
        make \
        vim \
        clang \
        libnuma-dev \
        libaio-dev \
        libboost-all-dev \
        libssl-dev \
        libjemalloc-dev \
        libhwloc-dev \
        python3 \
        python3-pip \
        python3-setuptools \
        python3-wheel

RUN apt install sudo -y

CMD ["/bin/bash"]